import { Oswald } from "next/font/google";
import "@/styles/globals.css";
import styles from './page.module.css'

const fontOswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700' ],
  display: "swap"
});


export const metadata = {
  title: "React 切版練習",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontOswald.variable}`}>
        <nav className={styles.nav}>
          <div className={styles.city}>Taipei</div>
        </nav>
        {children}
        <footer className={styles.footer}>
          source from:
          <a href="https://www.freepik.com/free-vector/weather-interface-flat-concept_2868698.htm#query=weather&position=20&from_view=search&track=sph" target="_blank">freepik.com</a>
        </footer>
      </body>
    </html>
  );
}
